networks:
  miga-search:
    driver: bridge

services:
  postgresql:
    image: bitnami/postgresql:latest
    networks:
      - miga-search
    environment:
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_POSTGRES_PASSWORD: password
    ports:
      - 5432:5432